// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZOKKwLQBkpiLlHv-MyydVWY3qafJ9CXY',
    appId: '1:984799256139:web:e61b07214ee6dcb75177ce',
    messagingSenderId: '984799256139',
    projectId: 'apss-22224',
    authDomain: 'apss-22224.firebaseapp.com',
    storageBucket: 'apss-22224.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVahUeHXuXc2UTSecs-ypPeQbVN-EpEEw',
    appId: '1:984799256139:android:5e2f9e53a05ce2f45177ce',
    messagingSenderId: '984799256139',
    projectId: 'apss-22224',
    storageBucket: 'apss-22224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTvUdhuIrnnOXmZ5Uikw2YpReqYL3mDrs',
    appId: '1:984799256139:ios:e7dde73dc9636f245177ce',
    messagingSenderId: '984799256139',
    projectId: 'apss-22224',
    storageBucket: 'apss-22224.firebasestorage.app',
    iosBundleId: 'com.example.aps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTvUdhuIrnnOXmZ5Uikw2YpReqYL3mDrs',
    appId: '1:984799256139:ios:e7dde73dc9636f245177ce',
    messagingSenderId: '984799256139',
    projectId: 'apss-22224',
    storageBucket: 'apss-22224.firebasestorage.app',
    iosBundleId: 'com.example.aps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZOKKwLQBkpiLlHv-MyydVWY3qafJ9CXY',
    appId: '1:984799256139:web:eb2674278e9b31995177ce',
    messagingSenderId: '984799256139',
    projectId: 'apss-22224',
    authDomain: 'apss-22224.firebaseapp.com',
    storageBucket: 'apss-22224.firebasestorage.app',
  );
}
