# Generated by Django 5.1.7 on 2025-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='passport',
            field=models.CharField(max_length=20, verbose_name='Passport Number'),
        ),
    ]
