# Generated by Django 5.1.7 on 2025-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Отправитель'),
        ),
    ]
