# Generated by Django 5.1.7 on 2025-04-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0002_alter_ordertracking_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='invoice_no',
            field=models.IntegerField(default=0, unique=True, verbose_name='Invoice № of order'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='order_code',
            field=models.CharField(default='No order code', max_length=10, unique=True, verbose_name='Code of order'),
        ),
    ]
