# Generated by Django 5.1.7 on 2025-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0003_ordertracking_invoice_no_ordertracking_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='birth_date',
            field=models.DateField(verbose_name='Birth Date'),
        ),
    ]
