# Generated by Django 5.1.7 on 2025-03-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0003_branch_receiver_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='email',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='email',
        ),
    ]
