# Generated by Django 5.1.7 on 2025-04-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0005_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertracking',
            old_name='receiver',
            new_name='receiver_name',
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
