# Generated by Django 5.1.7 on 2025-03-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0006_userdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Модель товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг категории')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_image/', verbose_name='Фото категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='aps_app.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг товара')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата Изменение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps_app.category', verbose_name='Категория товара')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aps_app.brand', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aps_app.product', verbose_name='Товар')),
            ],
        ),
    ]
