# Generated by Django 5.2 on 2025-04-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0007_alter_receiver_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Район'),
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
