# Generated by Django 5.2 on 2025-04-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0008_alter_city_options_alter_city_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codetved', models.CharField(max_length=10, verbose_name='Код ТН ВЭД')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('english', models.CharField(max_length=255, verbose_name='Название на английском')),
                ('russian', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('uzbek', models.CharField(max_length=255, verbose_name='Название на узбекском')),
                ('turkish', models.CharField(max_length=255, verbose_name='Название на турецком')),
            ],
            options={
                'verbose_name': 'Перевод продукта',
                'verbose_name_plural': 'Переводы продуктов',
                'ordering': ['codetved'],
            },
        ),
    ]
