# Generated by Django 5.1.7 on 2025-03-19 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0010_alter_product_discount_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='Описание отсутствует.', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(100)], verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100), django.core.validators.MaxLengthValidator(500)], verbose_name='Описание товара'),
        ),
    ]
