# Generated by Django 5.1.7 on 2025-03-20 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_app', '0011_product_short_description_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='region',
        ),
        migrations.CreateModel(
            name='OrderMoneyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.FloatField(default=0, verbose_name='Лимит на $1000')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_limits', to='aps_app.receiver', verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Улица')),
                ('weight', models.FloatField(default=0, verbose_name='Вес заказа')),
                ('full_price', models.FloatField(verbose_name='Общая сумма')),
                ('passport_id', models.CharField(max_length=10, verbose_name='Серия паспорта')),
                ('dof', models.CharField(max_length=20, verbose_name='Дата рождение')),
                ('notes', models.TextField(validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aps_app.city', verbose_name='Город')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='aps_app.receiver', verbose_name='Покупатель')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aps_app.region', verbose_name='Регион')),
                ('limit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aps_app.ordermoneylimit', verbose_name='Лимит')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
